version: 1
job:
  type: "ingestion"
source:
  endpoint: "test_lfs"
  properties:
    source_file_pattern: "/database"
    format: "delimited"
    charset: "UTF-8"
    partial_load: false
    format_properties:
      column_delimiter: ","
      quote_delimiter: "\""
      escape_char: "\\\\"
      contains_header: true
      infer_schema: true
      clean_column_name: false
      trim_white_space: "none"
schema:
  schema_derivation_strategy: "source"
  strict_schema_check: true
  discard: true
target:
  endpoint: "test_azureSQL"
  properties:
    format_properties:
      batch_size: 2500
      bulk_copy_timeout: 600
      isolation_level: "READ_COMMITTED"
      reliability_level: "BEST_EFFORT"
      table_lock: true
  operation: "append"
reject:
  endpoint: "test_hdfs"
  properties:
    format: "delimited"
    charset: "UTF-8"
    preserve_hierarchy: false
    format_properties:
      column_delimiter: ","
      quote_delimiter: "\""
      escape_char: "\\\\"
      contains_header: true
      merge_file: false
